spring:
  application:
    name: maxquant2saint

conversion:
  file: proteinGroups.txt
  fasta: human.fasta
  intensity: LFQ
  bait: '(.*)_\d+'
  control: 'FLAG.*'

maxquant:
  headers:
    protein-ids: Protein IDs
    gene-names: Gene names
    lfq: LFQ intensity (.*)
    msms-count: MS/MS count (.*)
    intensity: Intensity (.*)
    peptides: Peptides (.*)
    razor-peptides: Razor + unique peptides (.*)
    unique-peptides: Unique peptides (.*)
    coverage: Sequence coverage (.*) [%]

fasta:
  protein-id: '>.*\|(.*)\|'

logging:
  file: ${spring.application.name}.log

---
spring:
  profiles: test

logging:
  file: test.log
